version: '3.8'

services:
  web:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/canvas/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
      - minio

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=canvas
      - POSTGRES_PASSWORD=canvaspass
      - POSTGRES_DB=canvasdb

  minio:
    image: minio/minio
    command: server /data
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data:
