# Generated by Django 5.0.7 on 2024-09-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chipsample',
            name='autosomal_call_rate',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='chipsample',
            name='lrr_std_dev',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='chipsample',
            name='sex_estimate',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unknown')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='sex',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unknown')], max_length=100, null=True),
        ),
    ]
