# Generated by Django 5.0.7 on 2024-09-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canvas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chiptype",
            name="cols",
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name="chiptype",
            name="rows",
            field=models.IntegerField(default=12),
        ),
    ]
