# Generated by Django 5.0.7 on 2024-10-11 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0003_alter_chipsample_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chip',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='canvas.lot'),
        ),
    ]
