# Generated by Django 5.0.7 on 2024-10-14 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0004_alter_chip_lot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chipsample',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chipsample', to='canvas.sample'),
        ),
    ]
