# Generated by Django 5.0.7 on 2024-10-18 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canvas", "0005_alter_chipsample_sample"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="protocol_id",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_protocol_id",
                        message="Only alphanumeric characters",
                        regex="^[0-9a-zA-ZçÇğĞıİöÖşŞüÜ-_]*$",
                    )
                ],
            ),
        ),
    ]
