# Generated by Django 5.0.7 on 2024-10-22 10:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0006_alter_sample_protocol_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chiptype',
            name='band_path',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='chiptype',
            name='bpm_path',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='chiptype',
            name='csv_path',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='chiptype',
            name='egt_path',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='chiptype',
            name='fasta_path',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='chiptype',
            name='pfb_path',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sample',
            name='protocol_id',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_protocol_id', message='Only alphanumeric characters', regex='^[0-9a-zA-ZçÇğĞıİöÖşŞüÜ_-]*$')]),
        ),
    ]
