# Generated by Django 5.0.7 on 2024-10-23 11:43

import canvas.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0008_remove_chiptype_band_path_remove_chiptype_bpm_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chiptype',
            name='fasta_index',
            field=models.FileField(blank=True, upload_to=canvas.models.analysis_files_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['fai'])]),
        ),
    ]
