# Generated by Django 5.0.7 on 2024-10-23 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canvas", "0008_remove_chiptype_band_path_remove_chiptype_bpm_path_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sample",
            name="repeat",
        ),
        migrations.AddField(
            model_name="sample",
            name="repeat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="canvas.sample",
            ),
        ),
    ]
