# Generated by Django 5.0.7 on 2024-10-23 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canvas", "0009_remove_sample_repeat_sample_repeat"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="chipsample",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="report",
                to="canvas.chipsample",
            ),
        ),
    ]
